name: base_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  json_annotation: ^4.6.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1  
  flutter_flavorizr: ^2.1.4
  json_serializable: ^6.3.2

flavorizr:
  flavors:
    dev:
      app:
        name: "Dev App"
      android:
        applicationId: "com.example.apple"
      ios:
        bundleId: "com.example.apple"
    stg:
      app:
        name: "Stg App"
      android:
        applicationId: "com.example.banana"
      ios:
        bundleId: "com.example.banana"
    prod:
      app:
        name: "Prod App"
      android:
        applicationId: "com.example.banana"
      ios:
        bundleId: "com.example.banana"

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
